apiVersion: v1
kind: Secret
metadata:
  name: soil-module-secret
  namespace: nekazari
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "CHANGE_ME_MINIO_ACCESS_KEY"
  MINIO_SECRET_KEY: "CHANGE_ME_MINIO_SECRET_KEY"
  pg-dsn: "CHANGE_ME_POSTGRESQL_DSN"
