import os

ORION_BASE_URL = os.environ["ORION_BASE_URL"]
MINIO_ENDPOINT = os.environ["MINIO_ENDPOINT"]
MINIO_ACCESS_KEY = os.environ["MINIO_ACCESS_KEY"]
MINIO_SECRET_KEY = os.environ["MINIO_SECRET_KEY"]
REDIS_URL = os.environ["REDIS_URL"]
CONTEXT_URL = os.environ["CONTEXT_URL"]

CACHE_TTL_BASELINE = int(os.environ.get("CACHE_TTL_BASELINE", "31536000"))
CACHE_TTL_REVISABLE = int(os.environ.get("CACHE_TTL_REVISABLE", "2592000"))
INGESTION_BUFFER_M = float(os.environ.get("INGESTION_BUFFER_M", "50.0"))
PROVIDER_RETRY_MAX = int(os.environ.get("PROVIDER_RETRY_MAX", "5"))
PROVIDER_ISOLATE_SECONDS = int(os.environ.get("PROVIDER_ISOLATE_SECONDS", "900"))
